name: Run Security_bot_V2.0.1

on:
  workflow_dispatch: # អនុញ្ញាតឱ្យចុច Run ដោយផ្ទាល់
  schedule:
    - cron: '0 */5 * * *' # កំណត់ឱ្យ Trigger បន្តស្វ័យប្រវត្តិ

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Telegram Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
        run: |
          python bot.py
